{{- if .Values.networkPolicy.enabled -}}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "spring-boot-app.fullname" . }}
  labels:
    {{- include "spring-boot-app.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "spring-boot-app.selectorLabels" . | nindent 6 }}
  ingress:
  - from:
    - podSelector: {}
    ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
  egress:
  - {}
{{- end }}
