apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: sample-spring-boot-app-backstage
  title: sample-spring-boot-app-backstage
  annotations:
    github.com/project-slug: sourcefuse/arc-platform-spring-boot-app
    argocd/app-name: clm-app-qa
    argocd/proxy-url: '/argocd/api2'
    backstage.io/kubernetes-id: sample-spring-boot-app-backstage
    backstage.io/kubernetes-cluster: sourcekube3
    sonarqube.org/project-key: sourcefuse_bizbook-arc-iac
    jenkins.io/job-full-name: 'Oasis/QA
  tags:
    - spring-boot
    - java
    - maven
    - circleci
    - renovate
    - sonarqube
spec:
  type: service
  owner: devops@sourcefuse.com
  lifecycle: experimental
