apiVersion: apps/v1
kind: Deployment
metadata:
  name: person-service
spec:
  replicas: 3
  selector:
    matchLabels:
      app: person-service
  template:
    metadata:
      labels:
        app: person-service
    spec:
      containers:
      - name: person-service
        image: sample-spring-boot-app-backstage:latest
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: person-service
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: person-service