package pl.piomin.services.controller;

import org.instancio.Instancio;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.MethodOrderer;
import org.junit.jupiter.api.Order;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.TestMethodOrder;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.boot.test.web.client.TestRestTemplate;
import org.springframework.core.ParameterizedTypeReference;
import org.springframework.http.HttpEntity;
import org.springframework.http.HttpMethod;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import pl.piomin.services.domain.Person;

import java.util.List;

import static org.junit.jupiter.api.Assertions.*;

@SpringBootTest(webEnvironment = SpringBootTest.WebEnvironment.RANDOM_PORT)
@TestMethodOrder(MethodOrderer.OrderAnnotation.class)
public class PersonControllerTests {

    private static final String API_PATH = "/api/v1";
    private static Long createdPersonId;

    @Autowired
    private TestRestTemplate restTemplate;

    @Test
    @Order(1)
    @DisplayName("Should create a new person")
    void shouldCreatePerson() {
        // Arrange
        Person person = Instancio.create(Person.class);
        person.setId(null); // ID should be generated by the service
        
        // Act
        ResponseEntity<Person> response = restTemplate.postForEntity(API_PATH, person, Person.class);
        
        // Assert
        assertEquals(HttpStatus.CREATED, response.getStatusCode());
        assertNotNull(response.getBody());
        assertNotNull(response.getBody().getId());
        assertEquals(person.getFirstName(), response.getBody().getFirstName());
        assertEquals(person.getLastName(), response.getBody().getLastName());
        
        // Store ID for subsequent tests
        createdPersonId = response.getBody().getId();
    }

    @Test
    @Order(2)
    @DisplayName("Should get person by ID")
    void shouldGetPersonById() {
        // Act
        ResponseEntity<Person> response = restTemplate.getForEntity(API_PATH + "/" + createdPersonId, Person.class);
        
        // Assert
        assertEquals(HttpStatus.OK, response.getStatusCode());
        assertNotNull(response.getBody());
        assertEquals(createdPersonId, response.getBody().getId());
    }

    @Test
    @Order(3)
    @DisplayName("Should get all persons")
    void shouldGetAllPersons() {
        // Act
        ResponseEntity<List<Person>> response = restTemplate.exchange(
                API_PATH,
                HttpMethod.GET,
                null,
                new ParameterizedTypeReference<List<Person>>() {}
        );
        
        // Assert
        assertEquals(HttpStatus.OK, response.getStatusCode());
        assertNotNull(response.getBody());
        assertFalse(response.getBody().isEmpty());
        assertTrue(response.getBody().stream().anyMatch(p -> p.getId().equals(createdPersonId)));
    }

    @Test
    @Order(4)
    @DisplayName("Should update person")
    void shouldUpdatePerson() {
        // Arrange
        ResponseEntity<Person> getResponse = restTemplate.getForEntity(API_PATH + "/" + createdPersonId, Person.class);
        Person personToUpdate = getResponse.getBody();
        assertNotNull(personToUpdate);
        
        String updatedFirstName = "UpdatedFirstName";
        String updatedLastName = "UpdatedLastName";
        personToUpdate.setFirstName(updatedFirstName);
        personToUpdate.setLastName(updatedLastName);
        
        // Act
        HttpEntity<Person> requestEntity = new HttpEntity<>(personToUpdate);
        ResponseEntity<Person> response = restTemplate.exchange(
                API_PATH + "/" + createdPersonId,
                HttpMethod.PUT,
                requestEntity,
                Person.class
        );
        
        // Assert
        assertEquals(HttpStatus.OK, response.getStatusCode());
        assertNotNull(response.getBody());
        assertEquals(createdPersonId, response.getBody().getId());
        assertEquals(updatedFirstName, response.getBody().getFirstName());
        assertEquals(updatedLastName, response.getBody().getLastName());
    }

    @Test
    @Order(5)
    @DisplayName("Should find persons by first name")
    void shouldFindPersonsByFirstName() {
        // Arrange
        ResponseEntity<Person> getResponse = restTemplate.getForEntity(API_PATH + "/" + createdPersonId, Person.class);
        Person person = getResponse.getBody();
        assertNotNull(person);
        
        // Act
        ResponseEntity<List<Person>> response = restTemplate.exchange(
                API_PATH + "/search?firstName=" + person.getFirstName(),
                HttpMethod.GET,
                null,
                new ParameterizedTypeReference<List<Person>>() {}
        );
        
        // Assert
        assertEquals(HttpStatus.OK, response.getStatusCode());
        assertNotNull(response.getBody());
        assertFalse(response.getBody().isEmpty());
        assertTrue(response.getBody().stream().anyMatch(p -> p.getFirstName().equals(person.getFirstName())));
    }

    @Test
    @Order(6)
    @DisplayName("Should delete person")
    void shouldDeletePerson() {
        // Act
        restTemplate.delete(API_PATH + "/" + createdPersonId);
        
        // Assert - Verify person no longer exists
        ResponseEntity<Person> response = restTemplate.getForEntity(API_PATH + "/" + createdPersonId, Person.class);
        assertEquals(HttpStatus.NOT_FOUND, response.getStatusCode());
    }

    @Test
    @Order(7)
    @DisplayName("Should return 404 when person not found")
    void shouldReturn404WhenPersonNotFound() {
        // Act
        ResponseEntity<Person> response = restTemplate.getForEntity(API_PATH + "/999999", Person.class);
        
        // Assert
        assertEquals(HttpStatus.NOT_FOUND, response.getStatusCode());
    }

    @Test
    @Order(8)
    @DisplayName("Should handle invalid person data")
    void shouldHandleInvalidPersonData() {
        // Arrange
        Person invalidPerson = new Person();
        // Leave required fields empty
        
        // Act
        ResponseEntity<Person> response = restTemplate.postForEntity(API_PATH, invalidPerson, Person.class);
        
        // Assert
        assertEquals(HttpStatus.BAD_REQUEST, response.getStatusCode());
    }
}