# Move to the .github/workflows folder
name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        environment: [dev, staging, prod]
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'

    - name: Cache Maven packages
      uses: actions/cache@v2
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-

    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Run tests
      run: mvn test

    - name: Code coverage report
      run: mvn jacoco:report

    - name: Security scan
      run: mvn verify sonar:sonar
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

    - name: Build Docker image
      run: docker build . -t myapp:${{ github.sha }}

    - name: Push Docker image
      run: docker push myapp:${{ github.sha }}
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

    - name: Helm lint
      run: helm lint ./helm-chart

    - name: Deploy to Kubernetes
      if: github.ref == 'refs/heads/main' && matrix.environment == 'prod'
      run: |
        helm upgrade --install myapp ./helm-chart --namespace ${{ matrix.environment }}
        --set image.tag=${{ github.sha }}
      env:
        KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}

    - name: Notify Slack
      if: success()
      uses: slackapi/slack-github-action@v1.18.0
      with:
        payload: '{"text":"Deployment to ${{ matrix.environment }} successful!"}'
        channel-id: ${{ secrets.SLACK_CHANNEL }}
        slack-bot-token: ${{ secrets.SLACK_BOT_TOKEN }}